all:
	gcc -pthread -o pthread1 pthread1.c
	gcc -pthread -o pthread2 pthread2.c
	gcc -pthread -o pthread3 pthread3.c
	gcc -pthread -o pthread4 pthread4.c

clean:
	rm pthread1 pthread2 pthread3 pthread4
